// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPaLRbrBUkVndyHsITwB0w31ylRRkRLOw',
    appId: '1:1076429937427:web:c918a4f9cc308852ed58e6',
    messagingSenderId: '1076429937427',
    projectId: 'poke-scan-2748e',
    authDomain: 'poke-scan-2748e.firebaseapp.com',
    storageBucket: 'poke-scan-2748e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcAF9yrydRzYrHUtwLHeVn0YO2kY8D5fo',
    appId: '1:1076429937427:android:673a58bb7ca87755ed58e6',
    messagingSenderId: '1076429937427',
    projectId: 'poke-scan-2748e',
    storageBucket: 'poke-scan-2748e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARIEEQETrJK_oTxMHvNSCl9w9JPOouIDE',
    appId: '1:1076429937427:ios:5bb4162e87e2b955ed58e6',
    messagingSenderId: '1076429937427',
    projectId: 'poke-scan-2748e',
    storageBucket: 'poke-scan-2748e.firebasestorage.app',
    iosBundleId: 'com.example.pokeScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARIEEQETrJK_oTxMHvNSCl9w9JPOouIDE',
    appId: '1:1076429937427:ios:5bb4162e87e2b955ed58e6',
    messagingSenderId: '1076429937427',
    projectId: 'poke-scan-2748e',
    storageBucket: 'poke-scan-2748e.firebasestorage.app',
    iosBundleId: 'com.example.pokeScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPaLRbrBUkVndyHsITwB0w31ylRRkRLOw',
    appId: '1:1076429937427:web:56851e2dbda38c38ed58e6',
    messagingSenderId: '1076429937427',
    projectId: 'poke-scan-2748e',
    authDomain: 'poke-scan-2748e.firebaseapp.com',
    storageBucket: 'poke-scan-2748e.firebasestorage.app',
  );
}
